config/routes.rb
Rails.application.routes.draw do
  resources :view_data
  resources :taggings
  resources :tags
  resources :topics, except: :show
  resources :categories
  get 'topics/:topic', to: 'testimonials#index'


  resources :testimonials do
    resources :comments
  end

  # if route defined after, it will be interpreted as events/(:id = search)
  get 'events/search', as: 'search'
  # delete event or events with multi dates
  get 'events/delete/:id/:type_update(.:format)', to: 'events#destroy_events', as: 'delete_events'
  get 'events/:id/duplicate', to: 'events#duplicate', as: 'duplicate'
  get 'events/show2/:id', to: 'events#show2', as: 'show2'
  resources :events do
    resources :comments
  end

  get 'members/index_pros', as: 'pros'
  get 'members/index_amateurs', as: 'amateurs'
  patch 'members/:id', to: 'members#update'

  devise_for :members, controllers: {
    registrations: 'registrations',
    sessions: 'sessions',
    omniauth_callbacks: 'members/omniauth_callbacks'
  }

  get 'members/:id/edit', to: 'members#edit',  as: 'member_edit'

  devise_scope :member do
    resources :members, only: %i[show index] do
      resources :comments
    end
  end

  # Stripe
  # resources :charges

  get 'pages/home', as: 'home'
  get 'pages/team', as: 'team'
  get 'pages/pricing', as: 'pricing'
  get 'pages/smihug', as: 'smihug'
  get 'pages/contact', as: 'contact'
  get 'pages/news', as: 'news'
  get 'pages/cgu', as: 'cgu'
  get 'pages/confidentiality', as: 'confidentiality'
  post 'pages/contact', to: 'pages#send_mail_contact'
  get 'pages/forbidden', as: 'forbidden'
  get 'pages/permission', as: 'permission'
  get 'pages/test', as: 'test'
  get 'pages/errors_member', as: 'errors_member'
  get 'pages/home_awesome', as: 'home_awesome'
  get 'pages/faqs', as: 'faqs'
  root 'events#index'
end

app/controllers/events_controller.rb
require 'pry'


class EventsController < ApplicationController


  before_action :require_login, only: %i[new duplicate edit update destroy]
  before_action :set_event, only: %i[show edit duplicate update destroy show2]
  before_action :require_permission, only: %i[edit update destroy]
  before_action :set_list_events, only: %i[update destroy]
  after_action :list_categories, only: %i[create edit update destroy]

  # GET /events
  # GET /events.json
  def index
    @h1_title = 'Les propositions à venir'
    @events = Event.next_events
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @h1_title = @event.title
    @comment = Comment.new
  end

  def show2
    @h1_title = @event.title
    @comment = Comment.new
  end

  # GET /events/new
  def new
    @h1_title = 'Ajouter votre proposition'
    @event = Event.new
    @event.begin_at = @event.end_at = DateTime.now + 1.hours #local hour
    # $teachers is global because if !create return view with @teachers wrong
    $teachers = Member.all
    @category_list = current_member.category_list.sort.join(', ').to_s
  end

  # GET /events/duplicate/:id
  def duplicate
    @h1_title = 'Dupliquer cette proposition'
    # category_list is not in database table Event
    @category_list = @event.category_list.sort.join(', ').to_s
    @event = @event.dup
    @event.calendar_string = nil
    @event.multi_dates_id = nil
    @event.calendar_range_string = nil
    # $teachers is global because if !create return view with @teachers wrong
    $teachers = (Member.pros << current_member).reverse.uniq
    render :new
  end


  # GET /events/1/edit
  def edit
    @h1_title = 'Modifier ma proposition'
    @h1_title += 'Formulaire de l\'ADMINISTRATEUR ' if (current_member && current_member.has_role?(ROLE_ADMIN))
    $teachers = (Member.pros << current_member).reverse.uniq
    # must have @category_list in case duplicate
    @category_list = @event.category_list.join(', ').to_s
  end

  # POST /events
  # POST /events.json
  def create

    @event = Event.new(event_params)

    # if @event.cloudy already exist => duplicate else create from scratch
    @cloudy = @event.cloudy ? @event.cloudy : Cloudy.create
    @save_is_ok = true

    # dates is range
    if @event.calendar_range_string.size > 0

      @event = Event.new(event_params)
      @event.organizer = ( current_member.has_role?(ROLE_ADMIN) && @event.teacher) ? @event.teacher : current_member
      @event.cloudy = @cloudy
      @event.duration = @event.end_at - @event.begin_at
      # force image to avoid uplaod a new image per event created
      @save_is_ok &&= @event.save

      if @save_is_ok
        ContactMailer.new_user_action('Nouvel évènement', @event.url).deliver_now
        @event.reload
        @cloudy.identifier = @event.image.filename
        @cloudy.prefix_cloudinary = 'http://res.cloudinary.com/' + YAML.load_file('config/cloudinary.yml')['production']['cloud_name'] + '/'
        @cloudy.save
        @event.index!
      end

    elsif @event.calendar_string.size > 0

      # multi_dates_id = Time.new is Id group of all items
      tab_dates = @event.calendar_string.split(',')
      time_stamp = Time.new

      @save_is_ok = tab_dates.count > 0

      flash[:alert] = "Il faut choisir une ou plusieurs dates" unless @save_is_ok

      tab_dates.each do |d|
        @event = Event.new(event_params)
        @event.multi_dates_id = time_stamp if tab_dates.count > 1
        @event.organizer = ( current_member.has_role?(ROLE_ADMIN) && @event.teacher) ? @event.teacher : current_member

        @event.cloudy = @cloudy
        # if local zone = Paris, the 2 instruction follow add + hours in execution but not in debug
        # so DO NOT CHANGE LOCAL ZONE
        time_at = I18n.l(@event.begin_at, format: '%H:%M')
        @event.begin_at  = DateTime.strptime(d+' '+time_at, '%d/%m/%Y %H:%M')
        time_at = I18n.l(@event.end_at, format: '%H:%M')
        @event.end_at  = DateTime.strptime(d+' '+time_at, '%d/%m/%Y %H:%M')
        @event.duration = @event.end_at - @event.begin_at

        # save once to get cloudinary infos, break if save not ok
        break unless @save_is_ok &&= @event.save

        if @save_is_ok
          ContactMailer.new_user_action('Nouvel évènement', @event.url).deliver_now
          if !@cloudy.identifier
            @event.reload
            @cloudy.identifier = @event.image.filename
            @cloudy.prefix_cloudinary = 'http://res.cloudinary.com/' + YAML.load_file('config/cloudinary.yml')['production']['cloud_name'] + '/'
            @cloudy.save
            params[:event].delete(:image)
          end
          @event.index!
        end
      end
    end

    respond_to do |format|
      if @save_is_ok
        format.html { redirect_to @event}
        format.json { render :show, status: :created, location: @event }
      else
        # simple_form doesn t show errors for :begin_at & :end_at because
        flash[:alert] = "Problème dans la création de l événement"
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    # if delete, we need form to get type_upadte
    if params[:commit] == ACTION_SUPPRIMER
      destroy_events
      return
    end

    @update_is_ok = true
    @cloudy = Cloudy.new if params[:event][:image]
    @list_events.each do |event|
      @event = event
      @update_is_ok &&= @event.update(event_params)
      @event.duration = @event.end_at - @event.begin_at
      if @cloudy
        # init cloudy once with the first update
        unless @cloudy.identifier
          @event.reload
          @cloudy.identifier = @event.image.filename
          @cloudy.prefix_cloudinary = 'http://res.cloudinary.com/' + YAML.load_file('config/cloudinary.yml')['production']['cloud_name'] + '/'
          @cloudy.save
          params[:event].delete(:image)
        end
        @event.cloudy = @cloudy
      end
      @event.save
      @event.index!
    end

    respond_to do |format|
      if @update_is_ok
        format.html { redirect_to @event}
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end

  end

  def destroy_events

    @delete_is_ok = true
    @multi_dates_id = @event.multi_dates_id

    @list_events.each do |event|
      destroy(event)
    end

    set_update_calendar_string

    respond_to do |format|
      if @delete_is_ok
        format.html { redirect_to events_url}
        format.json { head :no_content }
      else
        # simple_form doesn t show errors for :begin_at & :end_at because
        flash.now[:alert] = "Problème dans la suppression de l'évènement"
        format.html { render @event }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # search by category
  def category
    if params[:category]
      # @testimonials = Testimonial.published.tagged_with(params[:topic])
      @events = Event.tagged_with(params[:category])
      redirect_to events_url(category: params[:category])
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy(event)
    @delete_is_ok &&= event.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Set the list of events / TYPE_UPADTE
  def set_list_events
    @list_events = case params[:type_update]
      when UPDATE_TYPE_ALL_ITEMS  then Event.where(multi_dates_id: @event.multi_dates_id)
      when UPDATE_TYPE_ALL_AFTER  then Event.where(multi_dates_id: @event.multi_dates_id).where("begin_at >= ?", @event.begin_at)
      else [@event]
      end
  end

  def event_params_date
    # if range, event during several days
    if params[:event][:calendar_range_string].size > 0
      calendar_range_string = params[:event][:calendar_range_string].delete(' ').split('-')

      @begin_at  = DateTime.strptime(calendar_range_string[0]+params[:event]["begin_at(4i)"]+params[:event]["begin_at(5i)"],
        '%d/%m/%Y%H%M')
      @end_at  = DateTime.strptime(calendar_range_string[1]+params[:event]["end_at(4i)"]+params[:event]["end_at(5i)"],
        '%d/%m/%Y%H%M')

    # mono or multidate for persisted event
    # if persisted & multi date & not range : not change the day but only hh:mm / destroy doesn't need @event but list_events
    elsif (@event && @event.persisted?) && (@event.multi_dates_id)
      # if persisted & multi date : not change the day but only hh:mm
        @begin_at = DateTime.new(@event.begin_at.year, @event.begin_at.month, @event.begin_at.day,
                                              params[:event]["begin_at(4i)"].to_i,params[:event]["begin_at(5i)"].to_i)

        @end_at = DateTime.new(@event.end_at.year, @event.end_at.month, @event.end_at.day,
                                              params[:event]["end_at(4i)"].to_i,params[:event]["end_at(5i)"].to_i)

    # elsif only one get the date in calendar_string
    elsif !params[:event][:calendar_string].include?(',')
        # day is given by calendar_string = 1 only date
        @begin_at = DateTime.strptime(params[:event][:calendar_string] + ' ' +
                                              params[:event]["begin_at(4i)"] + ':' + params[:event]["begin_at(5i)"],
                                              '%d/%m/%Y %H:%M')

        @end_at = DateTime.strptime(params[:event][:calendar_string] + ' ' +
                                              params[:event]["end_at(4i)"] + ':' + params[:event]["end_at(5i)"],
                                              '%d/%m/%Y %H:%M')
    # take the first date
    else
        @begin_at = DateTime.strptime(params[:event][:calendar_string].split(',')[0] + ' ' +
                                              params[:event]["begin_at(4i)"] + ':' + params[:event]["begin_at(5i)"],

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_sum_small.html.erb
<a href="<%= event.url %>">
<div class="featured-course-item w-dyn-item w-col w-col-3">
  <div class="course-block-wrapper home-featured">
    <div style="background-image:url(<%= event.image_url %>)" class="course-image-link-block home-featured w-inline-block" >
      <div class="teacher-overlay-block w-clearfix">
<!--               <img class="teacher-overlay-photo"> -->
        <%= cl_image_tag event.organizer.avatar, class: "teacher-overlay-photo" %>
        <div class="teacher-overlay-title"><%= event.organizer.pseudo %></div>
      </div>
      <div class="image-overlay-block">
        <div class="image-overlay-block w-clearfix">
          <div class="featured-label">
            <%= event.categories[0].name %>
          </div>
        </div>
      </div>
    </div>
    <div class="course-content-block">
      <div class="course-title-link" %>
        <%= event.short_title %>
      </div>
    </div>
    <div class="course-content-block _2">
      <div class="course-info-icon"><i class="material-icons" style="font-size: 16px; position:relative; top:3px">place</i></div>
      <div class="course-info-title"><%= event.zip %></div>
      <div class="course-info-icon"></div>
      <div class="course-info-title"><%= event.show_begin_at_hours %></div>
    </div>
  </div>
</div>
</a>

app/views/events/_events_search.html.erb
<br />
<div id="search-bar">
  <input type="text" class="form-control" id="search-box"></input>
  <div id="add_event">
    <% if member_signed_in? %>
      <%= link_to 'Ajouter une proposition', new_event_path, class: 'btn btn-default', style: 'font-weight: bold' %>
    <% else %>
      <%= link_to 'Ajouter une proposition', '#', 'data-toggle':'modal', 'data-target':'#connection', class: 'btn btn-default', style: 'font-size: 1.2em' %>
    <% end %>
  </div>
</div>
<br />

<div id="hits-container"></div>
<div id="pagination-container"></div>

<script src="https://cdn.jsdelivr.net/npm/instantsearch.js@1/dist/instantsearch.min.js"></script>

<script>
  var search = instantsearch({
    apiKey: '<%= ENV['ALGOLIA_SEARCH_API_KEY_SEARCH'] %>',
    appId: '<%= ENV['ALGOLIA_SEARCH_APPLICATION_ID'] %>',
    indexName: 'Event',
    searchParameters: {
      filters: 'unix_begin_at > <%= Time.now.to_i %>'
    }
  });

  search.addWidget(
    instantsearch.widgets.searchBox({
      container: '#search-box',
      placeholder: 'Entrez vos mots clés ...',
      autofocus: true
    })
  );

  var hitTemplate =
    '<br />' +
    '<table class="table">' +
      '<thead>' +
        '<tr><th>Les propositions</th><th>Date</th><th>Prix</th><th>Lieu</th><th>Orga.</th></tr>' +
      '</thead>' +
      '<tbody>' +
        '{{#hits}}' +
          '<tr onclick="document.location=\'{{url}}\'">' +
            '<td>{{short_title}}</td>' +
            '<td>{{show_begin_at}}</td>' +
            '<td>{{show_price}}</td>' +
            '<td>{{zip}}</td>' +
            '<td>' +
              '<img src="{{member_avatar}}" class="organizer"></img>' +
            '</td>' +
          '</tr>' +
        '{{/hits}}' +
      '</tbody>' +
    '</table>';

  var noResultsTemplate =
    '<div class="text-center">Nous n\'avons trouvé aucun résultat pour <strong>{{query}}</strong>.</div>';

  search.addWidget(
    instantsearch.widgets.hits({
      container: '#hits-container',
      templates: {
        empty: noResultsTemplate,
        allItems: hitTemplate
      },
      hitsPerPage: 20
    })
  );

  search.addWidget(
    instantsearch.widgets.pagination({
      container: '#pagination-container'
    })
  );

  search.start();

</script>

app/views/events/edit.html.erb
<div class="container">
  <%= render 'form', event: @event %>
</div>

app/views/events/index-webflow-OK.html.erb
  <div class="page-header courses">
    <div class="page-header-overlay">
      <div class="container w-container">
        <h2 data-ix="fade-in-on-load" class="page-header-title">Liste des propositions du mois à venir</h2>
        <h2 data-ix="fade-in-on-load-2" class="page-subtitle">Pour danser et s'épanouir à Paris</h2>
      </div>
    </div>
  </div>

  <div class="section">
    <div class="container w-container">
      <div>
      <%= link_to "Ajouter une proposition", new_event_path, class: "button submit-button w-button", style: "font-size: 100%; width:237px; margin:auto "%>
      </div>
      </br>
      </br>
      <div class="content">
        <%= render "events", list_events: @events %>
      </div>
    </div>
  </div>

app/views/events/index.js.erb
$("#events").html("<%= j render partial: 'events', locals: { events_partial: @events } %>");
$("#title").html("<%= @h1_title %>");
$(".btn_events").toggleClass("btn_selectable");

app/views/events/show-svg.html.erb
<%= stylesheet_link_tag 'event' %>
<p id="notice"><%= notice %></p>

<div class="container">
  <div id="show">
    <div id="event">
      <div id="event_title">
        <h4><%= @event.title %></h4>
        <div id="event_controls">
          <% if member_signed_in? && (current_member == @event.organizer) %>
            <%= link_to '(modifier)', edit_event_path %>
          <% end %>
          <%= link_to '(copier)', duplicate_path( @event), class: 'enable' %>
        </div>
      </div>

      <% if @event.cloudy.present? && @event.cloudy.identifier.present? %>
          <%= cl_image_tag @event.cloudy.identifier, width: 600, height: 182, crop: :fill %>
      <% end %>

      <div id="event_content">
        <%= link_to @event.organizer do %>
          <% if @event.organizer.avatar.file %>
            <%= cl_image_tag(@event.organizer.avatar.file.public_id, width: 80, radius: 20, id: 'avatar_organizer') %>
          <% end %>
        <% end %>

        <% if @event.teacher %>
          <%= link_to @event.teacher do %>
            <% if @event.teacher.avatar.file %>
              <%= cl_image_tag(@event.teacher.avatar.file.public_id, width: 80, radius: 20, id: 'avatar_teacher') %>
            <% end %>
          <% end %>
        <% end %>
        <table>
          <tr>
            <td>Date et heure</td>
            <td>: <%= @event.show_begin_at %></td>
          </tr>
          <tr>
            <td>Durée</td>
            <td>:
              <%= @event.show_duration %>
            </td>
          </tr>
          <tr>
            <td>Prix</td>
            <td>: <%= @event.show_price %></td>
          </tr>
          <tr>
            <td>Organisateur</td>
            <td>:
              <%= link_to @event.organizer.pseudo, @event.organizer, id: 'organizer' %>
            </td>
          </tr>
          <% if @event.teacher && (@event.teacher != @event.organizer) %>
            <tr>
              <td>Animateur</td>
              <td>:
                <%= link_to @event.teacher.pseudo, @event.teacher, id: 'teacher' %>
              </td>
            </tr>
          <% end %>
          <% if @event.place_name.to_s.size > 1 %>
            <td>Nom du lieu</td><td>: <%= @event.place_name.to_s %></td>
          <% end %>
          <tr>
            <td>Lieu</td>
            <td class="location pointer">:
              <%= link_to '#', 'data-toggle':'modal', 'data-target':'#modal_map', 'data-lat': @event.lat, 'data-lng': @event.lng do %>
                <% if @event.address.size > 50 %>
                  <%= @event.address[0..50] + ' (...)' %>
                <% else %>
                  <%= @event.address %>
                <% end %>
                <span class="location_icon glyphicon glyphicon-map-marker" aria-hidden="true"></span>
              <% end %>
            </td>
          </tr>
          <tr>
            <td>Description</td>
            <td>
              :
              <% if @event.description.size > 50 %>
                <%= link_to @event.description[0..50] + ' (...)', '#', 'data-toggle': 'modal', 'data-target': '#modal' %>
              <% else %>
                <%= @event.description %>
              <% end %>
            </td>
          </tr>
          <% if @event.note.to_s != '' %>
            <tr>
              <td>Remarques </td>
              <td>
                :
                <% if @event.note.size > 50 %>
                  <%= link_to @event.note[0..50] + ' (...)', '#', 'data-toggle': 'modal', 'data-target': '#modal_note' %>
                <% else %>
                  <%= @event.note %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>

    <div id="discussion">
      <h4>Poser une question à l'organisateur ou laisser un commentaire ici :</h4>
      <div id="comments">
        <% @event.comments.each do |comment| %>
            <%= render comment %>
        <% end %>
      </div>

      <%= simple_form_for [@event, @comment], remote: true do |f| %>
          <% if member_signed_in? %>
            <%= f.input :content, label: false %>
            <%= f.button :submit, 'Envoyer le commentaire' %>
          <% else %>
            <%= link_to  '#','data-toggle':'modal', 'data-target':'#connection' do %>
              <%= f.input :content, label: false %>
            <% end %>
            <%= link_to 'Envoyer le commentaire', '#', 'data-toggle':'modal', 'data-target':'#connection', class: 'btn btn-default' %>
          <% end %>
      <% end %>
    </div>
  </div>

  <% pictures = @event.return_pictures %>
  <% if pictures.size > 0 %>
    <div id="event_pictures">
      <% pictures.each do |picture| %>
        <%= link_to picture[:url], target: '_blank' do %>
          <%= cl_image_tag( picture[:filename], width: 200, height:200, radius: 10, crop: 'fill' ) %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<!-- Modals -->
<%= render 'layouts/modal', title: 'Description détaillée de <em>' + @event.title + '</em>', content: @event.description,
                            title_note: 'Note détaillée <em>' + @event.title + '</em>', content_note: @event.note %>

<%= render 'layouts/map', title: @event.address %>

<script>
  <% if @event.lat %>
    $('#modal_map').on('shown.bs.modal', function (event) {
      showMap($(event.relatedTarget).data('lat'), $(event.relatedTarget).data('lng'), $(event.relatedTarget).data('address'));
    });
  <% end %>
  $('#organizer').hover(
    function () {
      $('#avatar_organizer').show();
    },
    function () {
      $('#avatar_organizer').hide();
    },);

  $('#teacher').hover(
    function () {
      $('#avatar_teacher').show();
    },
    function () {
      $('#avatar_teacher').hide();
    },);
</script>

app/views/events/show.html.erb
  <div class="page-header course"  style="background-image: url(<%= @event.image_url %>)" >
    <div class="page-header-overlay course" >
      <div class="container course-header w-container">
        <h2 data-ix="fade-in-on-load" class="page-header-title course-title" style="width: 120%"><%= @event.title%> <%= @event.star.html_safe %></h2>
        <div>
          <div data-ix="fade-in-on-load-2" class="course-category-title">Categories : </div>
            <% if @event.categories.count > 0 %>
              <div data-ix="fade-in-on-load-2" class="course-category" href="" title="">
              <%= @event.categories.join(', ') %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="section tint event">
    <div class="container w-container">
      <div class="course-block-left">
        <div class="course-image-block w-clearfix" style="background-image: url(<%= @event.image_url %>)">
          <div class="featured-label"><%= @event.categories.first %></div>
        </div>
        <div class="course-info-block">
          <h4 class="section-title sidebar">Informations</h4>
          <div class="course-main-info-wrapper">
            <div class="main-course-info-title">Date</div>
            <div class="main-course-info-title info"><%= @event.show_begin_at_day %></div>
          </div>
          <div class="course-main-info-wrapper">
            <div class="main-course-info-title">Horaires</div>
            <div class="main-course-info-title info"><%= @event.show_begin_end %></div>
          </div>
          <div class="course-main-info-wrapper">
            <div class="main-course-info-title">Durée</div>
            <div class="main-course-info-title info"><%= @event.show_duration %></div>
          </div>
          <div class="course-main-info-wrapper">
            <div class="main-course-info-title">Prix</div>
            <div class="main-course-info-title info"><%= @event.show_price %></div>
          </div>
          <div class="course-main-info-wrapper">
            <div class="main-course-info-title">Lieu</div>
              <%= link_to '#', 'data-toggle':'modal', 'data-target':'#modal_map', 'data-lat': @event.lat, 'data-lng': @event.lng do %>
                <div class="main-course-info-title info">
                  <% if (@event.place_name.to_s.size > 0) %>
                    <div class="course-info-icon"><i class="material-icons" style="font-size: 16px; position:relative; top:3px">place</i></div>
                    <%= @event.place_name %></br>
                  <%end %>
                </div>
                <div class="main-course-info-title info">
                  <% if (@event.place_name.to_s.size == 0) %>
                    <i class="material-icons" style="font-size: 16px; position:relative; top:3px">place</i>
                  <%end %>
                  <%= @event.address %>
                </div>

                <div class="location_icon glyphicon glyphicon-map-marker" aria-hidden="true"></div>
              <% end %>
          </div>
          <div class="course-main-info-wrapper">
            <div class="main-course-info-title">Remarque</div>
            <div class="main-course-info-title info"><%= @event.note %></div>
          </div>
          <% if @event.discovery.to_i > 0 %>
            <div class="course-main-info-wrapper">
              <div class="main-course-info-title"> Places <%= @event.star.html_safe %></div>
              <div class="main-course-info-title info"><%= @event.discovery %></div>
            </div>
          <% end %>
        </div>
        <div class="course-info-block">
          <h4 class="section-title sidebar">Témoignages</h4>
          <div class="course-main-info-wrapper">
            <div class="main-course-info-title">Sur le même thème</div><a href="#">Ca m'intéresse</a></div>
          <div class="course-main-info-wrapper">
            <div class="main-course-info-title">Sur ce proposant</div><a href="#">Je veux voir</a></div>
        </div>
        <% if current_member && (current_member == @event.organizer) %>
          <div class="course-info-block with-button">
            <%= link_to("Modifier", edit_event_path, class: "button take-course w-button") %>
          </div>
        <% end %>
        <div class="course-info-block with-button">
          <%= link_to("Copier", duplicate_path, class: "button take-course w-button") %>
        </div>
      </div>
      <div class="course-main-info-block">
        <div class="course-content-wrapper">
          <div class="section-title-wrapper course">
            <h2 class="section-title">Description</h2>
            <div class="section-title-divider"></div>
          </div>
          <div class="course-description w-richtext"><%= simple_format(@event.description) %></div>
        </div>
        <div class="course-content-wrapper">
          <div class="section-title-wrapper course">
            <h2 class="section-title">
              <%= @event.organizer.male? ? 'Organisateur' : 'Organisatrice' %>
              <% if @event.teacher  && (@event.organizer != @event.teacher ) %>
              / <%= @event.organizer.male? ? 'Enseignant' : 'Enseignante' %>
              <% end %> </h2>
            <div class="section-title-divider"></div>
          </div>
          <div class="w-dyn-list">
            <div class="w-dyn-items w-row">

              <div class="teacher-block w-dyn-item w-col w-col-4">
                <div class="teacher-block-wrapper w-clearfix"><img class="teacher-class-photo" src="<%= @event.organizer_avatar %>" ><a class="teacher-title" href="<%= member_url(@event.organizer) %>"><%= @event.organizer.pseudo %></a>
                  <div class="teacher-title _2"><%= @event.organizer.title %></div>
                </div>
              </div>
              <% if @event.teacher && (@event.organizer != @event.teacher ) %>
                <div class="teacher-block w-dyn-item w-col w-col-4">
                  <div class="teacher-block-wrapper w-clearfix"><img class="teacher-class-photo" src="<%= @event.teacher_avatar %>" ><a class="teacher-title" href="<%= member_url(@event.teacher) %>"><%= @event.teacher.pseudo %></a>
                    <div class="teacher-title _2"><%= @event.teacher.title %></div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="section">
    <div class="container w-container">
      <div class="section-title-wrapper">
        <%= render 'comments/form', commentable: @event %>
      </div>
    </div>
  </div>
  <div class="section">
    <div class="container w-container">
      <div class="section-title-wrapper">
        <h2 class="section-title">Découvrir autres choses ?</h2>
        <h2 class="section-title subtitle">Ces cours pourraient aussi vous intéressez :</h2>
        <div class="section-title-divider"></div>
      </div>
      <div class="featured-courses-list-wrapper w-dyn-list">
        <div class="featured-courses-list w-clearfix w-dyn-items w-row">
          <% @list_short_events = Event.next_events.first(4) %>
             <%= render partial: 'events/event_sum_small', collection: @list_short_events, as: :event %>
        </div>
      </div>
    </div>
  </div>

<!-- Popup Google map -->
<%= render 'layouts/map', title: @event.address %>