config/routes.rb
Rails.application.routes.draw do
  resources :view_data
  resources :taggings
  resources :tags
  resources :topics, except: :show
  resources :categories
  get 'topics/:topic', to: 'testimonials#index'


  resources :testimonials do
    resources :comments
  end

  # if route defined after, it will be interpreted as events/(:id = search)
  get 'events/search', as: 'search'
  # delete event or events with multi dates
  get 'events/delete/:id/:type_update(.:format)', to: 'events#destroy_events', as: 'delete_events'
  get 'events/:id/duplicate', to: 'events#duplicate', as: 'duplicate'
  get 'events/show2/:id', to: 'events#show2', as: 'show2'
  resources :events do
    resources :comments
  end

  get 'members/index_pros', as: 'pros'
  get 'members/index_amateurs', as: 'amateurs'
  patch 'members/:id', to: 'members#update'

  devise_for :members, controllers: {
    registrations: 'registrations',
    sessions: 'sessions',
    omniauth_callbacks: 'members/omniauth_callbacks'
  }

  get 'members/:id/edit', to: 'members#edit',  as: 'member_edit'

  devise_scope :member do
    resources :members, only: %i[show index] do
      resources :comments
    end
  end

  # Stripe
  # resources :charges

  get 'pages/home', as: 'home'
  get 'pages/team', as: 'team'
  get 'pages/pricing', as: 'pricing'
  get 'pages/smihug', as: 'smihug'
  get 'pages/contact', as: 'contact'
  get 'pages/news', as: 'news'
  get 'pages/cgu', as: 'cgu'
  get 'pages/confidentiality', as: 'confidentiality'
  post 'pages/contact', to: 'pages#send_mail_contact'
  get 'pages/forbidden', as: 'forbidden'
  get 'pages/permission', as: 'permission'
  get 'pages/test', as: 'test'
  get 'pages/errors_member', as: 'errors_member'
  get 'pages/home_awesome', as: 'home_awesome'
  get 'pages/faqs', as: 'faqs'
  root 'events#index'
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
end

app/controllers/taggings_controller.rb
class TaggingsController < ApplicationController
  before_action :require_permission
  before_action :set_tagging, only: [:show, :edit, :update, :destroy]

  # GET /taggings
  # GET /taggings.json
  def index
    @taggings = Tagging.all
  end

  # GET /taggings/1
  # GET /taggings/1.json
  def show
  end

  # GET /taggings/new
  def new
    @tagging = Tagging.new
  end

  # GET /taggings/1/edit
  def edit
  end

  # POST /taggings
  # POST /taggings.json
  def create
    @tagging = Tagging.new(tagging_params)

    respond_to do |format|
      if @tagging.save
        format.html { redirect_to @tagging, notice: 'Tagging was successfully created.' }
        format.json { render :show, status: :created, location: @tagging }
      else
        format.html { render :new }
        format.json { render json: @tagging.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taggings/1
  # PATCH/PUT /taggings/1.json
  def update
    respond_to do |format|
      if @tagging.update(tagging_params)
        format.html { redirect_to @tagging, notice: 'Tagging was successfully updated.' }
        format.json { render :show, status: :ok, location: @tagging }
      else
        format.html { render :edit }
        format.json { render json: @tagging.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taggings/1
  # DELETE /taggings/1.json
  def destroy
    @tagging.destroy
    respond_to do |format|
      format.html { redirect_to taggings_url, notice: 'Tagging was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tagging
      @tagging = Tagging.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tagging_params
      params.require(:tagging).permit(:tag_id, :taggable_type, :taggable_id, :tagger_type, :tagger_id, :context)
    end

    def require_permission
      redirect_to permission_path unless current_member.has_role?(ROLE_ADMIN)
    end
end

app/views/taggings/_form.html.erb
<%= simple_form_for(@tagging) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :tag_id %>
    <%= f.input :taggable_type %>
    <%= f.input :taggable_id %>
    <%= f.input :tagger_type %>
    <%= f.input :tagger_id %>
    <%= f.input :context %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/taggings/edit.html.erb
<h1>Editing Tagging</h1>

<%= render 'form', tagging: @tagging %>

<%= link_to 'Show', @tagging %> |
<%= link_to 'Back', taggings_path %>

app/views/taggings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Taggings</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th>Taggable type</th>
      <th>Taggable</th>
      <th>Tagger type</th>
      <th>Tagger</th>
      <th>Context</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @taggings.each do |tagging| %>
      <tr>
        <td><%= tagging.tag_id %></td>
        <td><%= tagging.taggable_type %></td>
        <td><%= tagging.taggable_id %></td>
        <td><%= tagging.tagger_type %></td>
        <td><%= tagging.tagger_id %></td>
        <td><%= tagging.context %></td>
        <td><%= link_to 'Show', tagging %></td>
        <td><%= link_to 'Edit', edit_tagging_path(tagging) %></td>
        <td><%= link_to 'Destroy', tagging, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tagging', new_tagging_path %>

app/views/taggings/new.html.erb
<h1>New Tagging</h1>

<%= render 'form', tagging: @tagging %>

<%= link_to 'Back', taggings_path %>

app/views/taggings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @tagging.tag_id %>
</p>

<p>
  <strong>Taggable type:</strong>
  <%= @tagging.taggable_type %>
</p>

<p>
  <strong>Taggable:</strong>
  <%= @tagging.taggable_id %>
</p>

<p>
  <strong>Tagger type:</strong>
  <%= @tagging.tagger_type %>
</p>

<p>
  <strong>Tagger:</strong>
  <%= @tagging.tagger_id %>
</p>

<p>
  <strong>Context:</strong>
  <%= @tagging.context %>
</p>

<%= link_to 'Edit', edit_tagging_path(@tagging) %> |
<%= link_to 'Back', taggings_path %>