config/routes.rb
Rails.application.routes.draw do
  resources :view_data
  resources :taggings
  resources :tags
  resources :topics, except: :show
  resources :categories
  get 'topics/:topic', to: 'testimonials#index'


  resources :testimonials do
    resources :comments
  end

  # if route defined after, it will be interpreted as events/(:id = search)
  get 'events/search', as: 'search'
  # delete event or events with multi dates
  get 'events/delete/:id/:type_update(.:format)', to: 'events#destroy_events', as: 'delete_events'
  get 'events/:id/duplicate', to: 'events#duplicate', as: 'duplicate'
  get 'events/show2/:id', to: 'events#show2', as: 'show2'
  resources :events do
    resources :comments
  end

  get 'members/index_pros', as: 'pros'
  get 'members/index_amateurs', as: 'amateurs'
  patch 'members/:id', to: 'members#update'

  devise_for :members, controllers: {
    registrations: 'registrations',
    sessions: 'sessions',
    omniauth_callbacks: 'members/omniauth_callbacks'
  }

  get 'members/:id/edit', to: 'members#edit',  as: 'member_edit'

  devise_scope :member do
    resources :members, only: %i[show index] do
      resources :comments
    end
  end

  # Stripe
  # resources :charges

  get 'pages/home', as: 'home'
  get 'pages/team', as: 'team'
  get 'pages/pricing', as: 'pricing'
  get 'pages/smihug', as: 'smihug'
  get 'pages/contact', as: 'contact'
  get 'pages/news', as: 'news'
  get 'pages/cgu', as: 'cgu'
  get 'pages/confidentiality', as: 'confidentiality'
  post 'pages/contact', to: 'pages#send_mail_contact'
  get 'pages/forbidden', as: 'forbidden'
  get 'pages/permission', as: 'permission'
  get 'pages/test', as: 'test'
  get 'pages/errors_member', as: 'errors_member'
  get 'pages/home_awesome', as: 'home_awesome'
  get 'pages/faqs', as: 'faqs'
  root 'events#index'
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord

  include Rails.application.routes.url_helpers
  include AlgoliaSearch

  acts_as_taggable_on :topics, :members

  mount_uploader :image, ImageUploader

  belongs_to :author, class_name: 'Member'

  has_many :comments, as: :commentable
  has_many :authors, through: :comments

  scope :published, -> { where(published: true) }

  def self.showed
    if member_signed_in?
      list = (Testimonial.published + current_member.testimonials).uniq
    else
      list = Testimonial.published
    end
    return list
  end

  def self.by(member)
    Testimonial
    .where('author_id = ?', member.id)
  end

  def self.about(member)
    list = []
    Testimonial.published.each do |t|
      if t.member_list.include?(member.pseudo)
        list << t
      end
    end
    return list
  end

  def author_name
    self.author.name
  end

  def author_first_name
    self.author.first_name
  end

  def author_avatar
    return self.author.avatar.url
  end

  def author_pseudo
    return self.author.pseudo
  end

  def author_bio
    return self.author.bio
  end

  def url
     return ENV["ROOT_URL"] + testimonial_path(self)
  end

  def written_at
    I18n.l(self.created_at, format: '%a %-d %b %Y')
  end

  def interested_members
    interested_members = []
    interested_members << self.author
    interested_members += self.authors
    interested_members.uniq!
    return interested_members
  end

end

app/controllers/testimonials_controller.rb
require 'pry'

class TestimonialsController < ApplicationController
  before_action :set_testimonial, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: %i[new edit update destroy]
  before_action :require_permission, only: %i[edit update destroy]
  after_action :list_topics, only: %i[create edit update destroy]

  # GET /testimonials
  # GET /testimonials.json
  def index
    if params[:topic]
      @topic = params[:topic]
      @testimonials = (Testimonial.published.tagged_with(params[:topic]) +
        ( member_signed_in? ? current_member.testimonials.tagged_with(params[:topic]) : [] )).uniq.sort_by{|obj| obj.title}
    else
      @testimonials = (Testimonial.published +
        ( member_signed_in? ? current_member.testimonials : [] )).uniq.sort_by{|obj| obj.title}
    end
  end

  # GET /testimonials/1
  # GET /testimonials/1.json
  def show
    @h1_title = @testimonial.title
    @read_duration = [1, @testimonial.body.split.size / 250].max
    @comment = Comment.new
  end

  # GET /testimonials/new
  def new
    @h1_title = 'Ajouter votre témoignage'
    @testimonial = Testimonial.new
  end

  # GET /testimonials/1/edit
  def edit
  end

  # POST /testimonials
  # POST /testimonials.json
  def create
    @testimonial = Testimonial.new(testimonial_params)
    @testimonial.author = current_member
    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully created.' }
        format.json { render :show, status: :created, location: @testimonial }
        ContactMailer.new_user_action('Nouveau témoignage', @testimonial.url).deliver_now
      else
        format.html { render :new }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testimonials/1
  # PATCH/PUT /testimonials/1.json
  def update
    respond_to do |format|
      if @testimonial.update(testimonial_params)
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully updated.' }
        format.json { render :show, status: :ok, location: @testimonial }
      else
        format.html { render :edit }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.json
  def destroy
    @testimonial.destroy
    respond_to do |format|
      format.html { redirect_to testimonials_url, notice: 'Testimonial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    def require_login
      flash[:message] = "Il faut vous connecter pour créer un témoignage" if (action_name == 'new')
      flash[:message] = "Il faut vous connecter pour modifier un témoignage" if (action_name == 'edit')
      redirect_to new_member_session_path unless member_signed_in?
    end

    def require_permission
      redirect_to permission_path unless (@testimonial.author == current_member ||
            current_member.has_role?(ROLE_ADMIN))
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testimonial_params
      params.require(:testimonial).permit(:title, :body, :image, :published, :topic_list, :member_list, :tag, { tag_ids: [] }, :tag_ids)
    end

    # list testimonials showed for a member
    def list_showed
      if member_signed_in?
        list = (Testimonial.published + current_member.testimonials).uniq
      else
        list = Testimonial.published
      end
      return list
    end

    # set view_data topics for tags input
    def list_topics
      ViewDatum.topics
    end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<%= stylesheet_link_tag 'testimonial' %>
<%= stylesheet_link_tag 'form' %>
<%= stylesheet_link_tag 'remove_navbar_footer' %>

  <%= simple_form_for @testimonial, html: { class: 'purple_form', style: 'width: 100%;'} do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title, label: 'Le titre', required: true %>
      <%= f.input :body, as: :trix_editor, label: 'Votre texte', required: true, input_html: {rows: 5 }%>
      <!-- <%= f.input :image, required: true %> -->

      <%= f.label 'Thèmes' %>
      <%= f.input :topic_list, label: false, input_html:{id: 'topics', data:{role:'tagsinput'},
            value: f.object.topic_list.sort.join(', ').to_s} , placeholder: "Entrez des thèmes ..." %>

      <%= f.label 'Membres' %>
      <%= f.input :member_list, label: false, input_html:{id: 'members', data:{role:'tagsinput'},
                  value: f.object.member_list.sort.join(', ').to_s}, label: false, placeholder: "Entrez des pros ..."  %>

      <% if f.object.image.present? %>
        <%= cl_image_tag f.object.image.url, width: 60, height: 60, crop: :fill, radius: 5,  :border => { :width => 4, :color => "#553311" }, :gravity => :face %>
      <%= f.label 'Changer d\'image' %>
      <%= f.input :image, label: false %>
      <% else %>
      <%= f.label 'ajouter une image' %>
      <%= f.input :image, label: false  %>
      <% end %>

      <%= f.input :published, label: 'Publier maintenant' %>
    </div>

    <div class="form-actions btn-group btn-group-justified" role="group">
      <div class="btn-group" role="group">
        <%= f.button :submit, class: 'btn btn-primary btn-sm' %>
      </div>
      <div class="btn-group" role="group">
        <%= link_to 'Annuler', session[:request_back], class: 'btn btn-primary btn-sm' %>
      </div>
    </div>

  <% end %>
</div>


<script>

// constructs the suggestion engine
var tag_topics = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.whitespace,
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  // `tag_members` is an array of state names defined in "The Basics"
    local: <%= raw ViewDatum.find_by_data_type(VIEW_DATA_TOPICS).content %>
});

$('#topics').tagsinput({
  typeaheadjs: {
  source: tag_topics.ttAdapter()
  }
});

var tag_members = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.whitespace,
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  // local: <%= Member.all.as_json %>
  local: <%= raw Member.pseudos %>
});

tag_members.initialize();

var elt = $('#members');
elt.tagsinput({
  typeaheadjs: {
    source: tag_members.ttAdapter()
  }
});

</script>

app/views/testimonials/_info_index.html.erb
<% @info_title = "Pourquoi ces témoignages ?" %>
<% @info_content = "
        Ces textes ont été ecrits par des membres du site qui pensent que leurs récits pourraient vous éclairer d'une façon ou d'une autre sur leurs pratiques. Certaines d'elles sont peu connues et méritent qu'on prennent du temps pour expliquer ce qu'on peut y vivre.

        Il n'y a aucune promesse, aucune motivation à vous pousser de faire la même chose.

        Les auteurs se sont engagés à ne pas avoir été motivé par un avantage financier, en nature ou autre contre partie qui pourrait mettre en doute la sincérité et l'intégrité du témoignage.

        Seuls les témoignages positifs sont publiés. C'est arbitraire et complètement assumé. Nous ne cherchons pas à analyser objectivement une pratique. Au contraire, nous sommes ici dans le subjectif, l'arbitraire et d'un point de vu totalement personnel.

        Ces témoignages ont été rédigés à la manière d'une lettre d'un ami à un ami. C'est une expérience parmi d'autres. Elle est réelle. Elle est sincère.

        Nous espérons que vous aur
        "
%>

<%= render 'layouts/modal_info', title: @info_title, content: @info_content %>

app/views/testimonials/_info_new.html.erb
<% @info_title = "Pourquoi écrire un témoignage ?" %>
<% @info_content = "
                 Bonjour #{current_member.first_name},


          Nous nous réjouissons de votre venue sur cette page. Votre témoignage sera un partage d'expérience précieux. Un bout de votre vie que nous sommes impatients de découvrir.


          Ici, nous aimons les gens, les échanges chaleureux, les communications authentiques et les formulations simples. Ce que vous allez écrire ... et bien des membres vont le lire ! Peut-être que ce que vous avez vécu, ce que vous avez découvert pourrait parler à ces personnes, les toucher, leur donner envie d'essayer quelque chose de nouveau.


          Sur Bilobaba, nous adorons partager les expériences. Nous pouvons le faire par ces témoignages. Des petites lettres écrites par un ami pour un ami ... lu par de possibles futurs amis.


          Si vous n'avez pas au moins 15 minutes à consacrer à l'écriture de ce texte, alors vous pouvez revenir plus tard parce que nous ne sommes pas pressés. Nous voulons surtout lire un texte de qualité. Pas dans le sens littéraire du terme. Mais dans le sens authentique, vrai, de coeur à coeur.


          Si le lecteur ne passe pas au moins 5 minutes à vous lire, il ne sera pas connecté émotionnellement à votre histoire. Il pourra comprendre mais pas ressentir. Nous voulons des liens forts. Nous voulons donner l'espace pour de longs textes.


          Surtout, nous ne voulons pas de conseils parce qu'il y a déjà des sites très biens pour ça. Ce que nous voulons ? Des témoignages, des expériences, des paroles d'un voyageur qui nous raconte un bout de son aventure.
        "
%>

<%= render 'layouts/modal_info', title: @info_title, content: @info_content %>

app/views/testimonials/_testimonial.html.erb
<div class="blog-list-item w-dyn-item w-col w-col-6">
  <div class="blog-post-block">
    <%if testimonial.image_url %>
      <a class="blog-post-image-block w-inline-block" href=<%= testimonial_path(testimonial) %> style="background-image: url(<%= testimonial.image_url %>)" >
        <div class="image-overlay-block"></div>
      </a>
    <% else %>
      <a class="blog-post-image-block w-inline-block" href=<%= testimonial_path(testimonial) %> style="background-image: url(<%= testimonial.author.avatar_url %>)" href="#">
        <div class="image-overlay-block"></div>
      </a>
    <% end %>
    <div class="blog-post-content-block">
      <div class="blog-post-info-block blog-overview">
        <div class="course-info-icon"></div>
        <div class="blog-info-title"><%= date_sum(testimonial.created_at) %></div>
        <div class="course-info-icon"></div>
        <div class="blog-info-title"><%= testimonial.author.pseudo %></div>
      </div>
      <a class="blog-post-title-link blog-page" href=<%= testimonial_path(testimonial) %>><%= testimonial.title %></a>
      <div class="blog-post-summary">
        <div><%= simple_format(testimonial.body[0..200]) %></div>...
      </div>
      <%= link_to "Lire plus", testimonial_path(testimonial), class: "button blog-read-more w-button" %>
    </div>
  </div>
</div>

app/views/testimonials/edit.html.erb
<div class="container" style="width: 60%;font-size: 120%">

<%= render 'form', testimonial: @testimonial %>

</div>

app/views/testimonials/index.html.erb
  <div class="page-header courses-grid">
    <div class="page-header-overlay">
      <div class="container w-container">
        <h2 data-ix="fade-in-on-load" class="page-header-title">Les témoignages <% if @topic %> à propos de "<%= @topic %>"<% end %></h2>
        <h2 data-ix="fade-in-on-load-2" class="page-subtitle">Partages d'un ami à des amis pour montrer ce qui existe</h2>
      </div>
    </div>
  </div>
  <div class="section tint">
    <%= link_to "Ajouter un témoignage", new_testimonial_path, class: "button submit-button w-button", style: "font-size: 100%; width:237px; margin:auto "%>
    </br>
    <div class="container w-container">
      <div class="blog-list-wrapper w-dyn-list">
        <div class="blog-list w-clearfix w-dyn-items w-row">
          <%= render partial: 'testimonial', collection: @testimonials %>
        </div>
      </div>
    </div>
  </div>

app/views/testimonials/index2.html.erb
<div class="container">
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-lg" data-toggle="modal" data-target="#modal_info">
    Présentation
  </button>

  <div style="display: flex; justify-content: space-between;">
    <div>
      <h2>Les témoignages</h2>
    </div>
    <div>
      <% if member_signed_in? %>
        <%= link_to 'Ajouter votre témoignage', new_testimonial_path, class: 'btn btn-default', style: 'font-size: 110%' %>
      <% else %>
        <%= link_to  '#','data-toggle':'modal', 'data-target':'#connection', class: 'btn btn-default'  do %>
                  Ajouter votre témoignage
        <% end %>
      <% end %>
    </div>
  </div>
  <table class='table'>
    <thead>
      <tr>
        <th>Titre</th>
        <th>Auteur</th>
        <th>Thèmes</th>
      </tr>
    </thead>
    <tbody>
      <% @testimonials.each do |testimonial| %>
        <tr>
          <td><%= link_to testimonial.title, testimonial %></td>
          <td><%= link_to testimonial.author.pseudo, testimonial.author %></td>
          <td><%= raw testimonial.topic_list.map { |t| link_to t, topic_path(t), title: "les témoignages portant sur #{t}" }.join(', ') %></td>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if member_signed_in? %>
    <%= link_to 'Ajouter votre témoignage', new_testimonial_path, class: 'btn btn-default' %>
  <% else %>
    <%= link_to  '#','data-toggle':'modal', 'data-target':'#connection', class: 'btn btn-default'  do %>
              Ajouter votre témoignage
    <% end %>
  <% end %>

</div>

<%= render "info_index" %>

app/views/testimonials/new.html.erb
<div class="container" style="width: 60%;font-size: 120%">
   <button type="button" class="btn btn-lg" data-toggle="modal" data-target="#modal_info">
    Présentation
  </button>

<%= render 'form', testimonial: @testimonial %>

<hr/>

<%= render "info_new" %>

app/views/testimonials/show.html.erb
  <!-- <div class="page-header blog-post"  style="background-image:url(<%= @testimonial.image.url %>)"> -->
  <div class="page-header blog-post">
    <div class="page-header-overlay blog-post" >
      <div class="container w-container">
        <div class="blog-title-wrapper">
          <h2 data-ix="fade-in-on-load" class="page-header-title blog-post-title"><%= @testimonial.title %></h2>
          <div class="blog-post-header-info-block">
            <div data-ix="fade-in-on-load-2" class="course-category-title icon"></div>
            <div data-ix="fade-in-on-load-2" class="blog-post-date-title"><%= date_sum(@testimonial.created_at) %></div>
            <div data-ix="fade-in-on-load-2" class="course-category-title icon"></div>
            <%= link_to(@testimonial.author.pseudo, @testimonial.author, data: { ix: "fade-in-on-load-2" }, class: "blog-post-date-title") %>

            <div data-ix="fade-in-on-load-2" class="course-category-title icon"></div>
            <div data-ix="fade-in-on-load-2" class="blog-post-date-title"><%= @read_duration %> min de lecture</div>
            <% if current_member &&  (current_member == @testimonial.author) %>
                  <a data-ix="fade-in-on-load-2" href="<%= edit_testimonial_path(@testimonial) %>" class="button blog-read-more w-button"> Modifier</a>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="section tint">
    <div class="container w-container">
      <div class="blog-post-wrapper">
        <div class="blog-post-content-wrapper first">
          <div class="blog-post-content-block w-richtext">
            <%= @testimonial.body.html_safe %>
          </br>
            <%= cl_image_tag(@testimonial.image, width:'200%', height:'200%') %>
          </div>

          <div style="display: flex;">
            <div style = "font-size: 16px">
            Thèmes&nbspévoqués&nbsp:&nbsp
            </div>
            <div >
                <%= raw @testimonial.topic_list.sort.map { |t|  link_to t, topic_path(t), class: "tag-dark", title: "les témoignages portant sur #{t}" }.join(' ') %>
            </div>
          </div>
          <br />
          <div style="display: flex;">
            <div style = "font-size: 16px">
            Membres&nbspconcernés&nbsp:&nbsp
            </div>
            <div class="tags_css ">
                <% @testimonial.member_list.each do |t| %>
                  <% if Member.find_by_pseudo(t) %>
                    <% url = Member.find_by_pseudo(t).url %>
                  <% else %>
                    <% url = "#" %>
                  <% end %>
                  <%= link_to(t, url, class: "tag-dark") %>
                <% end %>
            </div>

          </div>

          <br />

          <% if current_member && (current_member == @testimonial.author) %>
          <h5>
            Publié (visible par les autres) : <%= @testimonial.published ? 'Oui' : 'Non' %>
          </h5>
          <% end %>
        </div>
        <div class="blog-post-content-wrapper w-clearfix"><img class="blog-author-photo" src="<%= @testimonial.author.avatar_url %>">
          <div class="blog-author-title w-hidden-tiny">Témoignage écrit par :</div>
          <%= link_to(@testimonial.author.pseudo, @testimonial.author, class: "blog-author-title-link") %>
          <div class="blog-author-title job-title"><%= @testimonial.author.title %></div>
        </div>
          <%= render 'comments/form', commentable: @testimonial %>
      </div>
    </div>
  </div>

app/views/testimonials/show2.html.erb
<%= stylesheet_link_tag 'testimonial' %>


<div class="container" style="display: block;">
<div class="center-block">
<div style="margin: auto; width: 80%; background-color: khaki; padding: 25px; border-radius: 5px">
<h2 style="text-align: center;">
  <%= @testimonial.title %>
</h2>
<h4 style="text-align: center;">
  par <%= link_to @testimonial.author.pseudo, @testimonial.author %>
</h4>
<br />
<br />
<hr style="border: 1px solid darkolivegreen; width: 80%; text-align: center; margin: auto"/>
<br />
<br />
<div style="line-height: 2; font-size: 130%; width: 90%; margin: auto; ">
  <%= @testimonial.body.html_safe %>
</div>
<br />
<br />

<div style="display: flex;">
  <div style = "font-size: 16px">
  Thèmes évoqués : &nbsp
  </div>
  <div class="tags_css">
      <%= raw @testimonial.topic_list.sort.map { |t|  link_to t, topic_path(t), title: "les témoignages portant sur #{t}" }.join(' ') %>
  </div>
</div>
<br />
<div style="display: flex;">
  <div style = "font-size: 16px">
  Membres concernés :&nbsp
  </div>
  <div class="tags_css ">
      <% @testimonial.member_list.each do |t| %>
        <% if Member.find_by_pseudo(t) %>
          <% url = Member.find_by_pseudo(t).url %>
        <% else %>
          <% url = request.url %>
        <% end %>
        <%= link_to(t, url) %>
      <% end %>
  </div>

</div>

<br />
<h4>
  Publié : <%= @testimonial.published ? 'Oui' : 'Non' %>
</h4>
<!-- <p>
  <strong>Image: xxx</strong>
  <%= cl_image_tag @testimonial.image.url, width: 600, height: 182, crop: :fit %>
</p> -->

<br />
<% if current_member && @testimonial.author %>
  <%= link_to 'Modifier', edit_testimonial_path(@testimonial), class: "btn btn-default" %>
  <%= link_to 'Supprimer', @testimonial, method: :delete, data: { confirm: 'Etes-vous sûr ?' }, class: "btn btn-default"  %>
<% end %>
</div>
</div>
</div>